export const Singlechatdata = [
    {
        id: 1,
        personName: "John Doe",
        personProfileImage: "https://picsum.photos/seed/1/150",
        personLastmessage: "Hey, how are you?",
        unreadMessageCount: 2,
        lastMessageTime: "10:30 AM",
    },
    {
        id: 2,
        personName: "Jane Smith",
        personProfileImage: "https://picsum.photos/seed/2/150",
        personLastmessage: "Meeting at 2 PM.",
        unreadMessageCount: 0,
        lastMessageTime: "Yesterday",
    },
    {
        id: 3,
        personName: "Alice Johnson",
        personProfileImage: "https://picsum.photos/seed/3/150",
        personLastmessage: "Don't forget the report.",
        unreadMessageCount: 1,
        lastMessageTime: "Monday",
    },
    {
        id: 4,
        personName: "Bob Williams",
        personProfileImage: "https://picsum.photos/seed/4/150",
        personLastmessage: "See you tomorrow!",
        unreadMessageCount: 0,
        lastMessageTime: "Tuesday",
    },
    {
        id: 5,
        personName: "Charlie Brown",
        personProfileImage: "https://picsum.photos/seed/5/150",
        personLastmessage: "Got it, thanks.",
        unreadMessageCount: 3,
        lastMessageTime: "11:00 AM",
    },
    {
        id: 6,
        personName: "Diana Prince",
        personProfileImage: "https://picsum.photos/seed/6/150",
        personLastmessage: "Call me later.",
        unreadMessageCount: 0,
        lastMessageTime: "Wednesday",
    },
    {
        id: 7,
        personName: "Clark Kent",
        personProfileImage: "https://picsum.photos/seed/7/150",
        personLastmessage: "Working on it now.",
        unreadMessageCount: 1,
        lastMessageTime: "Thursday",
    },
    {
        id: 8,
        personName: "Bruce Wayne",
        personProfileImage: "https://picsum.photos/seed/8/150",
        personLastmessage: "Emergency meeting.",
        unreadMessageCount: 5,
        lastMessageTime: "Friday",
    },
    {
        id: 9,
        personName: "Tony Stark",
        personProfileImage: "https://picsum.photos/seed/9/150",
        personLastmessage: "Avengers assemble!",
        unreadMessageCount: 0,
        lastMessageTime: "Saturday",
    },
    {
        id: 10,
        personName: "Steve Rogers",
        personProfileImage: "https://picsum.photos/seed/10/150",
        personLastmessage: "On your left.",
        unreadMessageCount: 0,
        lastMessageTime: "Sunday",
    },
    {
        id: 11,
        personName: "Natasha Romanoff",
        personProfileImage: "https://picsum.photos/seed/11/150",
        personLastmessage: "Under control.",
        unreadMessageCount: 2,
        lastMessageTime: "09:00 AM",
    },
    {
        id: 12,
        personName: "Thor Odinson",
        personProfileImage: "https://picsum.photos/seed/12/150",
        personLastmessage: "Bring me Thanos!",
        unreadMessageCount: 0,
        lastMessageTime: "Yesterday",
    },
    {
        id: 13,
        personName: "Peter Parker",
        personProfileImage: "https://picsum.photos/seed/13/150",
        personLastmessage: "My spider-sense is tingling.",
        unreadMessageCount: 1,
        lastMessageTime: "Monday",
    },
    {
        id: 14,
        personName: "Wanda Maximoff",
        personProfileImage: "https://picsum.photos/seed/14/150",
        personLastmessage: "It's not fair.",
        unreadMessageCount: 0,
        lastMessageTime: "Tuesday",
    },
    {
        id: 15,
        personName: "Vision",
        personProfileImage: "https://picsum.photos/seed/15/150",
        personLastmessage: "A thing is not beautiful because it lasts.",
        unreadMessageCount: 0,
        lastMessageTime: "12:00 PM",
    },
    {
        id: 16,
        personName: "Stephen Strange",
        personProfileImage: "https://picsum.photos/seed/16/150",
        personLastmessage: "We're in the endgame now.",
        unreadMessageCount: 4,
        lastMessageTime: "Wednesday",
    },
    {
        id: 17,
        personName: "Gamora",
        personProfileImage: "https://picsum.photos/seed/17/150",
        personLastmessage: "I am going to die surrounded by the biggest idiots in the galaxy.",
        unreadMessageCount: 0,
        lastMessageTime: "Thursday",
    },
    {
        id: 18,
        personName: "Drax the Destroyer",
        personProfileImage: "https://picsum.photos/seed/18/150",
        personLastmessage: "Nothing goes over my head. My reflexes are too fast.",
        unreadMessageCount: 0,
        lastMessageTime: "Friday",
    },
    {
        id: 19,
        personName: "Rocket Raccoon",
        personProfileImage: "https://picsum.photos/seed/19/150",
        personLastmessage: "I am Groot.",
        unreadMessageCount: 1,
        lastMessageTime: "Saturday",
    },
    {
        id: 20,
        personName: "Groot",
        personProfileImage: "https://picsum.photos/seed/20/150",
        personLastmessage: "I am Groot.",
        unreadMessageCount: 0,
        lastMessageTime: "Sunday",
    },
    {
        id: 21,
        personName: "Scott Lang",
        personProfileImage: "https://picsum.photos/seed/21/150",
        personLastmessage: "Is this a new Avenger?",
        unreadMessageCount: 0,
        lastMessageTime: "01:00 PM",
    },
    {
        id: 22,
        personName: "Hope van Dyne",
        personProfileImage: "https://picsum.photos/seed/22/150",
        personLastmessage: "I'm not a cat.",
        unreadMessageCount: 2,
        lastMessageTime: "Yesterday",
    },
    {
        id: 23,
        personName: "T'Challa",
        personProfileImage: "https://picsum.photos/seed/23/150",
        personLastmessage: "Wakanda Forever!",
        unreadMessageCount: 0,
        lastMessageTime: "Monday",
    },
    {
        id: 24,
        personName: "Okoye",
        personProfileImage: "https://picsum.photos/seed/24/150",
        personLastmessage: "I am loyal to the throne, no matter who sits on it.",
        unreadMessageCount: 0,
        lastMessageTime: "Tuesday",
    },
    {
        id: 25,
        personName: "Shuri",
        personProfileImage: "https://picsum.photos/seed/25/150",
        personLastmessage: "Don't you 'hey Auntie' me.",
        unreadMessageCount: 1,
        lastMessageTime: "03:00 PM",
    },
    {
        id: 26,
        personName: "Sam Wilson",
        personProfileImage: "https://picsum.photos/seed/26/150",
        personLastmessage: "On your left.",
        unreadMessageCount: 0,
        lastMessageTime: "Wednesday",
    },
    {
        id: 27,
        personName: "Bucky Barnes",
        personProfileImage: "https://picsum.photos/seed/27/150",
        personLastmessage: "I'm with you 'til the end of the line.",
        unreadMessageCount: 0,
        lastMessageTime: "Thursday",
    },
    {
        id: 28,
        personName: "Carol Danvers",
        personProfileImage: "https://picsum.photos/seed/28/150",
        personLastmessage: "Higher, further, faster, baby.",
        unreadMessageCount: 3,
        lastMessageTime: "Friday",
    },
    {
        id: 29,
        personName: "Nick Fury",
        personProfileImage: "https://picsum.photos/seed/29/150",
        personLastmessage: "I've got my eye on you.",
        unreadMessageCount: 0,
        lastMessageTime: "Saturday",
    },
    {
        id: 30,
        personName: "Maria Hill",
        personProfileImage: "https://picsum.photos/seed/30/150",
        personLastmessage: "Everything is under control.",
        unreadMessageCount: 0,
        lastMessageTime: "Sunday",
    },
    {
        id: 31,
        personName: "Pepper Potts",
        personProfileImage: "https://picsum.photos/seed/31/150",
        personLastmessage: "I got him. I got him.",
        unreadMessageCount: 1,
        lastMessageTime: "05:00 PM",
    },
    {
        id: 32,
        personName: "Happy Hogan",
        personProfileImage: "https://picsum.photos/seed/32/150",
        personLastmessage: "Kids these days.",
        unreadMessageCount: 0,
        lastMessageTime: "Yesterday",
    },
    {
        id: 33,
        personName: "M'Baku",
        personProfileImage: "https://picsum.photos/seed/33/150",
        personLastmessage: "Glory to the Jabari!",
        unreadMessageCount: 0,
        lastMessageTime: "Monday",
    },
    {
        id: 34,
        personName: "Korg",
        personProfileImage: "https://picsum.photos/seed/34/150",
        personLastmessage: "Hey, I'm Korg. We're gonna get you to the ship.",
        unreadMessageCount: 2,
        lastMessageTime: "Tuesday",
    },
    {
        id: 35,
        personName: "Valkyrie",
        personProfileImage: "https://picsum.photos/seed/35/150",
        personLastmessage: "I'm not a hero.",
        unreadMessageCount: 0,
        lastMessageTime: "07:00 PM",
    },
    {
        id: 36,
        personName: "Loki Laufeyson",
        personProfileImage: "https://picsum.photos/seed/36/150",
        personLastmessage: "I am a god, you dull creature!",
        unreadMessageCount: 0,
        lastMessageTime: "Wednesday",
    },
    {
        id: 37,
        personName: "Hela",
        personProfileImage: "https://picsum.photos/seed/37/150",
        personLastmessage: "I am Hela, goddess of death.",
        unreadMessageCount: 1,
        lastMessageTime: "Thursday",
    },
    {
        id: 38,
        personName: "Odin Borson",
        personProfileImage: "https://picsum.photos/seed/38/150",
        personLastmessage: "Asgard is not a place. It's a people.",
        unreadMessageCount: 0,
        lastMessageTime: "Friday",
    },
    {
        id: 39,
        personName: "Heimdall",
        personProfileImage: "https://picsum.photos/seed/39/150",
        personLastmessage: "All-seeing, all-hearing.",
        unreadMessageCount: 0,
        lastMessageTime: "Saturday",
    },
    {
        id: 40,
        personName: "Stan Lee",
        personProfileImage: "https://picsum.photos/seed/40/150",
        personLastmessage: "Excelsior!",
        unreadMessageCount: 5,
        lastMessageTime: "Sunday",
    },
    {
        id: 41,
        personName: "Janet van Dyne",
        personProfileImage: "https://picsum.photos/seed/41/150",
        personLastmessage: "It's about damn time.",
        unreadMessageCount: 0,
        lastMessageTime: "09:00 AM",
    },
    {
        id: 42,
        personName: "Hank Pym",
        personProfileImage: "https://picsum.photos/seed/42/150",
        personLastmessage: "My science is better than your science.",
        unreadMessageCount: 0,
        lastMessageTime: "Yesterday",
    },
    {
        id: 43,
        personName: "Crossbones",
        personProfileImage: "https://picsum.photos/seed/43/150",
        personLastmessage: "This is for the Winter Soldier.",
        unreadMessageCount: 1,
        lastMessageTime: "Monday",
    },
    {
        id: 44,
        personName: "Red Skull",
        personProfileImage: "https://picsum.photos/seed/44/150",
        personLastmessage: "Hail Hydra!",
        unreadMessageCount: 0,
        lastMessageTime: "Tuesday",
    },
    {
        id: 45,
        personName: "Baron Zemo",
        personProfileImage: "https://picsum.photos/seed/45/150",
        personLastmessage: "An empire toppled by its enemies can rise again. But one which crumbles from within, that's dead forever.",
        unreadMessageCount: 0,
        lastMessageTime: "11:00 AM",
    },
    {
        id: 46,
        personName: "Ultron",
        personProfileImage: "https://picsum.photos/seed/46/150",
        personLastmessage: "There are no strings on me.",
        unreadMessageCount: 2,
        lastMessageTime: "Wednesday",
    },
    {
        id: 47,
        personName: "Thanos",
        personProfileImage: "https://picsum.photos/seed/47/150",
        personLastmessage: "I am inevitable.",
        unreadMessageCount: 0,
        lastMessageTime: "Thursday",
    },
    {
        id: 48,
        personName: "Nebula",
        personProfileImage: "https://picsum.photos/seed/48/150",
        personLastmessage: "I am going to kill you.",
        unreadMessageCount: 0,
        lastMessageTime: "Friday",
    },
    {
        id: 49,
        personName: "Ronan the Accuser",
        personProfileImage: "https://picsum.photos/seed/49/150",
        personLastmessage: "You cannot stop us!",
        unreadMessageCount: 1,
        lastMessageTime: "Saturday",
    },
    {
        id: 50,
        personName: "Korath the Pursuer",
        personProfileImage: "https://picsum.photos/seed/50/150",
        personLastmessage: "Who?",
        unreadMessageCount: 0,
        lastMessageTime: "Sunday",
    },
    {
        id: 51,
        personName: "Taneleer Tivan",
        personProfileImage: "https://picsum.photos/seed/51/150",
        personLastmessage: "One of a kind.",
        unreadMessageCount: 0,
        lastMessageTime: "01:00 PM",
    },
    {
        id: 52,
        personName: "Yondu Udonta",
        personProfileImage: "https://picsum.photos/seed/52/150",
        personLastmessage: "I'm Mary Poppins, y'all!",
        unreadMessageCount: 3,
        lastMessageTime: "Yesterday",
    },
    {
        id: 53,
        personName: "Ego the Living Planet",
        personProfileImage: "https://picsum.photos/seed/53/150",
        personLastmessage: "I am Ego.",
        unreadMessageCount: 0,
        lastMessageTime: "Monday",
    },
    {
        id: 54,
        personName: "Ayesha",
        personProfileImage: "https://picsum.photos/seed/54/150",
        personLastmessage: "All gold everything.",
        unreadMessageCount: 0,
        lastMessageTime: "Tuesday",
    },
    {
        id: 55,
        personName: "Christine Palmer",
        personProfileImage: "https://picsum.photos/seed/55/150",
        personLastmessage: "Stephen, you're a doctor, not a god.",
        unreadMessageCount: 1,
        lastMessageTime: "03:00 PM",
    },
    {
        id: 56,
        personName: "Wong",
        personProfileImage: "https://picsum.photos/seed/56/150",
        personLastmessage: "Just Wong.",
        unreadMessageCount: 0,
        lastMessageTime: "Wednesday",
    },
    {
        id: 57,
        personName: "Ancient One",
        personProfileImage: "https://picsum.photos/seed/57/150",
        personLastmessage: "You're a man looking at the world through a keyhole.",
        unreadMessageCount: 0,
        lastMessageTime: "Thursday",
    },
    {
        id: 58,
        personName: "Kaecilius",
        personProfileImage: "https://picsum.photos/seed/58/150",
        personLastmessage: "The world is not what you think it is.",
        unreadMessageCount: 2,
        lastMessageTime: "Friday",
    },
    {
        id: 59,
        personName: "Dormammu",
        personProfileImage: "https://picsum.photos/seed/59/150",
        personLastmessage: "I've come to bargain.",
        unreadMessageCount: 0,
        lastMessageTime: "Saturday",
    },
    {
        id: 60,
        personName: "Ghost Rider",
        personProfileImage: "https://picsum.photos/seed/60/150",
        personLastmessage: "Penance Stare!",
        unreadMessageCount: 0,
        lastMessageTime: "Sunday",
    },
    {
        id: 61,
        personName: "Jessica Jones",
        personProfileImage: "https://picsum.photos/seed/61/150",
        personLastmessage: "I'm a private investigator.",
        unreadMessageCount: 1,
        lastMessageTime: "09:00 AM",
    },
    {
        id: 62,
        personName: "Luke Cage",
        personProfileImage: "https://picsum.photos/seed/62/150",
        personLastmessage: "Sweet Christmas!",
        unreadMessageCount: 0,
        lastMessageTime: "Yesterday",
    },
    {
        id: 63,
        personName: "Danny Rand",
        personProfileImage: "https://picsum.photos/seed/63/150",
        personLastmessage: "I am the Iron Fist.",
        unreadMessageCount: 0,
        lastMessageTime: "Monday",
    },
    {
        id: 64,
        personName: "Matt Murdock",
        personProfileImage: "https://picsum.photos/seed/64/150",
        personLastmessage: "I'm not a hero. I'm just trying to make my city a better place.",
        unreadMessageCount: 4,
        lastMessageTime: "Tuesday",
    },
    {
        id: 65,
        personName: "Frank Castle",
        personProfileImage: "https://picsum.photos/seed/65/150",
        personLastmessage: "One Batch, Two Batch, Penny and Dime.",
        unreadMessageCount: 0,
        lastMessageTime: "12:00 PM",
    },
    {
        id: 66,
        personName: "Wilson Fisk",
        personProfileImage: "https://picsum.photos/seed/66/150",
        personLastmessage: "I am the Kingpin.",
        unreadMessageCount: 0,
        lastMessageTime: "Wednesday",
    },
    {
        id: 67,
        personName: "Elektra Natchios",
        personProfileImage: "https://picsum.photos/seed/67/150",
        personLastmessage: "I'm not your soldier.",
        unreadMessageCount: 1,
        lastMessageTime: "Thursday",
    },
    {
        id: 68,
        personName: "Colleen Wing",
        personProfileImage: "https://picsum.photos/seed/68/150",
        personLastmessage: "I know kung fu.",
        unreadMessageCount: 0,
        lastMessageTime: "Friday",
    },
    {
        id: 69,
        personName: "Misty Knight",
        personProfileImage: "https://picsum.photos/seed/69/150",
        personLastmessage: "I'm a cop.",
        unreadMessageCount: 0,
        lastMessageTime: "Saturday",
    },
    {
        id: 70,
        personName: "Jericho Drumm",
        personProfileImage: "https://picsum.photos/seed/70/150",
        personLastmessage: "Brother Voodoo.",
        unreadMessageCount: 3,
        lastMessageTime: "Sunday",
    },
    {
        id: 71,
        personName: "Blade",
        personProfileImage: "https://picsum.photos/seed/71/150",
        personLastmessage: "Some motherf***ers are always trying to ice-skate uphill.",
        unreadMessageCount: 0,
        lastMessageTime: "02:00 PM",
    },
    {
        id: 72,
        personName: "Morbius",
        personProfileImage: "https://picsum.photos/seed/72/150",
        personLastmessage: "I am the living vampire.",
        unreadMessageCount: 0,
        lastMessageTime: "Yesterday",
    },
    {
        id: 73,
        personName: "Werewolf by Night",
        personProfileImage: "https://picsum.photos/seed/73/150",
        personLastmessage: "Grrr...",
        unreadMessageCount: 1,
        lastMessageTime: "Monday",
    },
    {
        id: 74,
        personName: "Man-Thing",
        personProfileImage: "https://picsum.photos/seed/74/150",
        personLastmessage: "Whatever knows fear burns at the Man-Thing's touch!",
        unreadMessageCount: 0,
        lastMessageTime: "Tuesday",
    },
    {
        id: 75,
        personName: "Elsa Bloodstone",
        personProfileImage: "https://picsum.photos/seed/75/150",
        personLastmessage: "Monsters are real.",
        unreadMessageCount: 0,
        lastMessageTime: "04:00 PM",
    },
    {
        id: 76,
        personName: "Moon Knight",
        personProfileImage: "https://picsum.photos/seed/76/150",
        personLastmessage: "I am the vengeance of Khonshu!",
        unreadMessageCount: 2,
        lastMessageTime: "Wednesday",
    },
    {
        id: 77,
        personName: "She-Hulk",
        personProfileImage: "https://picsum.photos/seed/77/150",
        personLastmessage: "Don't make me angry. You wouldn't like me when I'm angry.",
        unreadMessageCount: 0,
        lastMessageTime: "Thursday",
    },
    {
        id: 78,
        personName: "Daredevil",
        personProfileImage: "https://picsum.photos/seed/78/150",
        personLastmessage: "I'm not looking for forgiveness for what I've done, Father. I'm asking for forgiveness for what I'm about to do.",
        unreadMessageCount: 0,
        lastMessageTime: "Friday",
    },
    {
        id: 79,
        personName: "Echo",
        personProfileImage: "https://picsum.photos/seed/79/150",
        personLastmessage: "I'm not a villain.",
        unreadMessageCount: 1,
        lastMessageTime: "Saturday",
    },
    {
        id: 80,
        personName: "Hawkeye",
        personProfileImage: "https://picsum.photos/seed/80/150",
        personLastmessage: "I have a family.",
        unreadMessageCount: 0,
        lastMessageTime: "Sunday",
    },
    {
        id: 81,
        personName: "Kate Bishop",
        personProfileImage: "https://picsum.photos/seed/81/150",
        personLastmessage: "I'm Hawkeye.",
        unreadMessageCount: 0,
        lastMessageTime: "06:00 PM",
    },
    {
        id: 82,
        personName: "Yelena Belova",
        personProfileImage: "https://picsum.photos/seed/82/150",
        personLastmessage: "It was a good plan.",
        unreadMessageCount: 3,
        lastMessageTime: "Yesterday",
    },
    {
        id: 83,
        personName: "Ms. Marvel",
        personProfileImage: "https://picsum.photos/seed/83/150",
        personLastmessage: "I'm a superhero!",
        unreadMessageCount: 0,
        lastMessageTime: "Monday",
    },
    {
        id: 84,
        personName: "Photon",
        personProfileImage: "https://picsum.photos/seed/84/150",
        personLastmessage: "I'm not Monica.",
        unreadMessageCount: 0,
        lastMessageTime: "Tuesday",
    },
    {
        id: 85,
        personName: "Nick Fury (Secret Invasion)",
        personProfileImage: "https://picsum.photos/seed/85/150",
        personLastmessage: "Trust no one.",
        unreadMessageCount: 1,
        lastMessageTime: "08:00 PM",
    },
    {
        id: 86,
        personName: "Talos",
        personProfileImage: "https://picsum.photos/seed/86/150",
        personLastmessage: "We're not the bad guys.",
        unreadMessageCount: 0,
        lastMessageTime: "Wednesday",
    },
    {
        id: 87,
        personName: "G'iah",
        personProfileImage: "https://picsum.photos/seed/87/150",
        personLastmessage: "I'm stronger than you think.",
        unreadMessageCount: 0,
        lastMessageTime: "Thursday",
    },
    {
        id: 88,
        personName: "Captain America (Sam Wilson)",
        personProfileImage: "https://picsum.photos/seed/88/150",
        personLastmessage: "I'm Captain America.",
        unreadMessageCount: 2,
        lastMessageTime: "Friday",
    },
    {
        id: 89,
        personName: "Bucky Barnes (Winter Soldier)",
        personProfileImage: "https://picsum.photos/seed/89/150",
        personLastmessage: "Who the hell is Bucky?",
        unreadMessageCount: 0,
        lastMessageTime: "Saturday",
    },
    {
        id: 90,
        personName: "Black Widow (Yelena)",
        personProfileImage: "https://picsum.photos/seed/90/150",
        personLastmessage: "It was a good plan.",
        unreadMessageCount: 0,
        lastMessageTime: "Sunday",
    },
    {
        id: 91,
        personName: "Shang-Chi",
        personProfileImage: "https://picsum.photos/seed/91/150",
        personLastmessage: "I'm just a busboy.",
        unreadMessageCount: 1,
        lastMessageTime: "10:00 AM",
    },
    {
        id: 92,
        personName: "Katy Chen",
        personProfileImage: "https://picsum.photos/seed/92/150",
        personLastmessage: "Best friend goals!",
        unreadMessageCount: 0,
        lastMessageTime: "Yesterday",
    },
    {
        id: 93,
        personName: "Xialing",
        personProfileImage: "https://picsum.photos/seed/93/150",
        personLastmessage: "You can't escape your past.",
        unreadMessageCount: 0,
        lastMessageTime: "Monday",
    },
    {
        id: 94,
        personName: "Wenwu",
        personProfileImage: "https://picsum.photos/seed/94/150",
        personLastmessage: "I am the Mandarin.",
        unreadMessageCount: 3,
        lastMessageTime: "Tuesday",
    },
    {
        id: 95,
        personName: "Xu Xialing (Leader)",
        personProfileImage: "https://picsum.photos/seed/95/150",
        personLastmessage: "The Ten Rings are mine now.",
        unreadMessageCount: 0,
        lastMessageTime: "12:00 PM",
    },
    {
        id: 96,
        personName: "Simu Liu",
        personProfileImage: "https://picsum.photos/seed/96/150",
        personLastmessage: "I can do this all day.",
        unreadMessageCount: 0,
        lastMessageTime: "Wednesday",
    },
    {
        id: 97,
        personName: "Awkwafina",
        personProfileImage: "https://picsum.photos/seed/97/150",
        personLastmessage: "I'm here for the snacks.",
        unreadMessageCount: 1,
        lastMessageTime: "Thursday",
    },
    {
        id: 98,
        personName: "Michelle Yeoh",
        personProfileImage: "https://picsum.photos/seed/98/150",
        personLastmessage: "We protect our own.",
        unreadMessageCount: 0,
        lastMessageTime: "Friday",
    },
    {
        id: 99,
        personName: "Benedict Wong",
        personProfileImage: "https://picsum.photos/seed/99/150",
        personLastmessage: "Just Wong.",
        unreadMessageCount: 0,
        lastMessageTime: "Saturday",
    },
    {
        id: 100,
        personName: "Destin Daniel Cretton",
        personProfileImage: "https://picsum.photos/seed/100/150",
        personLastmessage: "It's all about family.",
        unreadMessageCount: 5,
        lastMessageTime: "Sunday",
    },
];